[package]
name = "solidity_plonk_verifier"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "codegen",
    "codegen-bin"
]
default-members = [
    "codegen-bin"
]

[[bin]]
name = "generate"
path = "codegen-bin/src/main.rs"