[package]
name = "codegen"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
# franklin_crypto = {package = "franklin-crypto", path = "../../../matter-labs/franklin-crypto"}
# rescue_poseidon = {package = "rescue_poseidon", path = "../../../matter-labs/rescue-poseidon"}
franklin_crypto = {package = "franklin-crypto", git = "ssh://git@github.com/matter-labs/franklin-crypto", features = ["plonk"], branch = "dev"}
rescue_poseidon = {git = "ssh://git@github.com/matter-labs/rescue-poseidon"}
# sync_vm = {git = "ssh://git@github.com/matter-labs/sync_vm", branch = "dev"}
# sync_vm = {path = "../../sync_vm"}
hex = "*"   
paste = "1.0"